postgresql: &postgresql
  adapter: postgresql
  encoding: utf8
  min_messages: warning
  pool: 5
  # host: localhost
  # port: 5432
  # username: postgres
  # password:

development:
  <<: *postgresql
  database: stockmgr_development

production:
  <<: *postgresql
  database: stockmgr_production

test: &TEST
  <<: *postgresql
  database: stockmgr_test

cucumber:
  <<: *TEST
