require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ProductPricesController do

  # This should return the minimal set of attributes required to create a valid
  # ProductPrice. As you add validations to ProductPrice, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProductPricesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all product_prices as @product_prices" do
      product_price = ProductPrice.create! valid_attributes
      get :index, {}, valid_session
      assigns(:product_prices).should eq([product_price])
    end
  end

  describe "GET show" do
    it "assigns the requested product_price as @product_price" do
      product_price = ProductPrice.create! valid_attributes
      get :show, {:id => product_price.to_param}, valid_session
      assigns(:product_price).should eq(product_price)
    end
  end

  describe "GET new" do
    it "assigns a new product_price as @product_price" do
      get :new, {}, valid_session
      assigns(:product_price).should be_a_new(ProductPrice)
    end
  end

  describe "GET edit" do
    it "assigns the requested product_price as @product_price" do
      product_price = ProductPrice.create! valid_attributes
      get :edit, {:id => product_price.to_param}, valid_session
      assigns(:product_price).should eq(product_price)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ProductPrice" do
        expect {
          post :create, {:product_price => valid_attributes}, valid_session
        }.to change(ProductPrice, :count).by(1)
      end

      it "assigns a newly created product_price as @product_price" do
        post :create, {:product_price => valid_attributes}, valid_session
        assigns(:product_price).should be_a(ProductPrice)
        assigns(:product_price).should be_persisted
      end

      it "redirects to the created product_price" do
        post :create, {:product_price => valid_attributes}, valid_session
        response.should redirect_to(ProductPrice.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved product_price as @product_price" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductPrice.any_instance.stub(:save).and_return(false)
        post :create, {:product_price => {}}, valid_session
        assigns(:product_price).should be_a_new(ProductPrice)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ProductPrice.any_instance.stub(:save).and_return(false)
        post :create, {:product_price => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested product_price" do
        product_price = ProductPrice.create! valid_attributes
        # Assuming there are no other product_prices in the database, this
        # specifies that the ProductPrice created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ProductPrice.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => product_price.to_param, :product_price => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested product_price as @product_price" do
        product_price = ProductPrice.create! valid_attributes
        put :update, {:id => product_price.to_param, :product_price => valid_attributes}, valid_session
        assigns(:product_price).should eq(product_price)
      end

      it "redirects to the product_price" do
        product_price = ProductPrice.create! valid_attributes
        put :update, {:id => product_price.to_param, :product_price => valid_attributes}, valid_session
        response.should redirect_to(product_price)
      end
    end

    describe "with invalid params" do
      it "assigns the product_price as @product_price" do
        product_price = ProductPrice.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductPrice.any_instance.stub(:save).and_return(false)
        put :update, {:id => product_price.to_param, :product_price => {}}, valid_session
        assigns(:product_price).should eq(product_price)
      end

      it "re-renders the 'edit' template" do
        product_price = ProductPrice.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ProductPrice.any_instance.stub(:save).and_return(false)
        put :update, {:id => product_price.to_param, :product_price => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested product_price" do
      product_price = ProductPrice.create! valid_attributes
      expect {
        delete :destroy, {:id => product_price.to_param}, valid_session
      }.to change(ProductPrice, :count).by(-1)
    end

    it "redirects to the product_prices list" do
      product_price = ProductPrice.create! valid_attributes
      delete :destroy, {:id => product_price.to_param}, valid_session
      response.should redirect_to(product_prices_url)
    end
  end

end
