require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SalesOrderItemsController do

  # This should return the minimal set of attributes required to create a valid
  # SalesOrderItem. As you add validations to SalesOrderItem, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SalesOrderItemsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all sales_order_items as @sales_order_items" do
      sales_order_item = SalesOrderItem.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sales_order_items).should eq([sales_order_item])
    end
  end

  describe "GET show" do
    it "assigns the requested sales_order_item as @sales_order_item" do
      sales_order_item = SalesOrderItem.create! valid_attributes
      get :show, {:id => sales_order_item.to_param}, valid_session
      assigns(:sales_order_item).should eq(sales_order_item)
    end
  end

  describe "GET new" do
    it "assigns a new sales_order_item as @sales_order_item" do
      get :new, {}, valid_session
      assigns(:sales_order_item).should be_a_new(SalesOrderItem)
    end
  end

  describe "GET edit" do
    it "assigns the requested sales_order_item as @sales_order_item" do
      sales_order_item = SalesOrderItem.create! valid_attributes
      get :edit, {:id => sales_order_item.to_param}, valid_session
      assigns(:sales_order_item).should eq(sales_order_item)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SalesOrderItem" do
        expect {
          post :create, {:sales_order_item => valid_attributes}, valid_session
        }.to change(SalesOrderItem, :count).by(1)
      end

      it "assigns a newly created sales_order_item as @sales_order_item" do
        post :create, {:sales_order_item => valid_attributes}, valid_session
        assigns(:sales_order_item).should be_a(SalesOrderItem)
        assigns(:sales_order_item).should be_persisted
      end

      it "redirects to the created sales_order_item" do
        post :create, {:sales_order_item => valid_attributes}, valid_session
        response.should redirect_to(SalesOrderItem.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sales_order_item as @sales_order_item" do
        # Trigger the behavior that occurs when invalid params are submitted
        SalesOrderItem.any_instance.stub(:save).and_return(false)
        post :create, {:sales_order_item => {}}, valid_session
        assigns(:sales_order_item).should be_a_new(SalesOrderItem)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SalesOrderItem.any_instance.stub(:save).and_return(false)
        post :create, {:sales_order_item => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sales_order_item" do
        sales_order_item = SalesOrderItem.create! valid_attributes
        # Assuming there are no other sales_order_items in the database, this
        # specifies that the SalesOrderItem created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SalesOrderItem.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => sales_order_item.to_param, :sales_order_item => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested sales_order_item as @sales_order_item" do
        sales_order_item = SalesOrderItem.create! valid_attributes
        put :update, {:id => sales_order_item.to_param, :sales_order_item => valid_attributes}, valid_session
        assigns(:sales_order_item).should eq(sales_order_item)
      end

      it "redirects to the sales_order_item" do
        sales_order_item = SalesOrderItem.create! valid_attributes
        put :update, {:id => sales_order_item.to_param, :sales_order_item => valid_attributes}, valid_session
        response.should redirect_to(sales_order_item)
      end
    end

    describe "with invalid params" do
      it "assigns the sales_order_item as @sales_order_item" do
        sales_order_item = SalesOrderItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SalesOrderItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => sales_order_item.to_param, :sales_order_item => {}}, valid_session
        assigns(:sales_order_item).should eq(sales_order_item)
      end

      it "re-renders the 'edit' template" do
        sales_order_item = SalesOrderItem.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SalesOrderItem.any_instance.stub(:save).and_return(false)
        put :update, {:id => sales_order_item.to_param, :sales_order_item => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sales_order_item" do
      sales_order_item = SalesOrderItem.create! valid_attributes
      expect {
        delete :destroy, {:id => sales_order_item.to_param}, valid_session
      }.to change(SalesOrderItem, :count).by(-1)
    end

    it "redirects to the sales_order_items list" do
      sales_order_item = SalesOrderItem.create! valid_attributes
      delete :destroy, {:id => sales_order_item.to_param}, valid_session
      response.should redirect_to(sales_order_items_url)
    end
  end

end
