require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SalesOrdersController do

  # This should return the minimal set of attributes required to create a valid
  # SalesOrder. As you add validations to SalesOrder, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SalesOrdersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all sales_orders as @sales_orders" do
      sales_order = SalesOrder.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sales_orders).should eq([sales_order])
    end
  end

  describe "GET show" do
    it "assigns the requested sales_order as @sales_order" do
      sales_order = SalesOrder.create! valid_attributes
      get :show, {:id => sales_order.to_param}, valid_session
      assigns(:sales_order).should eq(sales_order)
    end
  end

  describe "GET new" do
    it "assigns a new sales_order as @sales_order" do
      get :new, {}, valid_session
      assigns(:sales_order).should be_a_new(SalesOrder)
    end
  end

  describe "GET edit" do
    it "assigns the requested sales_order as @sales_order" do
      sales_order = SalesOrder.create! valid_attributes
      get :edit, {:id => sales_order.to_param}, valid_session
      assigns(:sales_order).should eq(sales_order)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SalesOrder" do
        expect {
          post :create, {:sales_order => valid_attributes}, valid_session
        }.to change(SalesOrder, :count).by(1)
      end

      it "assigns a newly created sales_order as @sales_order" do
        post :create, {:sales_order => valid_attributes}, valid_session
        assigns(:sales_order).should be_a(SalesOrder)
        assigns(:sales_order).should be_persisted
      end

      it "redirects to the created sales_order" do
        post :create, {:sales_order => valid_attributes}, valid_session
        response.should redirect_to(SalesOrder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sales_order as @sales_order" do
        # Trigger the behavior that occurs when invalid params are submitted
        SalesOrder.any_instance.stub(:save).and_return(false)
        post :create, {:sales_order => {}}, valid_session
        assigns(:sales_order).should be_a_new(SalesOrder)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SalesOrder.any_instance.stub(:save).and_return(false)
        post :create, {:sales_order => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sales_order" do
        sales_order = SalesOrder.create! valid_attributes
        # Assuming there are no other sales_orders in the database, this
        # specifies that the SalesOrder created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SalesOrder.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => sales_order.to_param, :sales_order => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested sales_order as @sales_order" do
        sales_order = SalesOrder.create! valid_attributes
        put :update, {:id => sales_order.to_param, :sales_order => valid_attributes}, valid_session
        assigns(:sales_order).should eq(sales_order)
      end

      it "redirects to the sales_order" do
        sales_order = SalesOrder.create! valid_attributes
        put :update, {:id => sales_order.to_param, :sales_order => valid_attributes}, valid_session
        response.should redirect_to(sales_order)
      end
    end

    describe "with invalid params" do
      it "assigns the sales_order as @sales_order" do
        sales_order = SalesOrder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SalesOrder.any_instance.stub(:save).and_return(false)
        put :update, {:id => sales_order.to_param, :sales_order => {}}, valid_session
        assigns(:sales_order).should eq(sales_order)
      end

      it "re-renders the 'edit' template" do
        sales_order = SalesOrder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SalesOrder.any_instance.stub(:save).and_return(false)
        put :update, {:id => sales_order.to_param, :sales_order => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sales_order" do
      sales_order = SalesOrder.create! valid_attributes
      expect {
        delete :destroy, {:id => sales_order.to_param}, valid_session
      }.to change(SalesOrder, :count).by(-1)
    end

    it "redirects to the sales_orders list" do
      sales_order = SalesOrder.create! valid_attributes
      delete :destroy, {:id => sales_order.to_param}, valid_session
      response.should redirect_to(sales_orders_url)
    end
  end

end
